const tasks = [
  {
    id: 1,
    title: "Clean the house",
    description: "Vacuum, mop floors, dust surfaces",
    dueDate: "2023-06-15",
    priority: "high",
    completed: false,
  },
  {
    id: 2,
    title: "Grocery shopping",
    description: "Buy fruits, vegetables, milk, bread",
    dueDate: "2023-06-12",
    priority: "medium",
    completed: false,
  },
  {
    id: 3,
    title: "Pay bills",
    description: "Pay electricity, water, and internet bills",
    dueDate: "2023-06-20",
    priority: "high",
    completed: false,
  },
  {
    id: 4,
    title: "Exercise",
    description: "Go for a run or hit the gym",
    dueDate: "2023-06-14",
    priority: "medium",
    completed: false,
  },
  {
    id: 5,
    title: "Read a book",
    description: "Finish reading the novel you started",
    dueDate: "2023-06-30",
    priority: "low",
    completed: false,
  },
  {
    id: 6,
    title: "Call family",
    description: "Check in with parents and siblings",
    dueDate: "2023-06-18",
    priority: "medium",
    completed: false,
  },
  {
    id: 7,
    title: "Organize closet",
    description: "Sort through clothes and donate unwanted items",
    dueDate: "2023-07-01",
    priority: "low",
    completed: false,
  },
  {
    id: 8,
    title: "Meal prep",
    description: "Cook meals for the week ahead",
    dueDate: "2023-06-11",
    priority: "medium",
    completed: false,
  },
  {
    id: 9,
    title: "Attend meeting",
    description: "Prepare agenda and materials for team meeting",
    dueDate: "2023-06-16",
    priority: "high",
    completed: false,
  },
  {
    id: 10,
    title: "Car maintenance",
    description: "Get an oil change and tire rotation",
    dueDate: "2023-06-25",
    priority: "medium",
    completed: false,
  },
  {
    id: 11,
    title: "Laundry",
    description: "Wash, dry, and fold clothes",
    dueDate: "2023-06-13",
    priority: "medium",
    completed: false,
  },
  {
    id: 12,
    title: "Yard work",
    description: "Mow the lawn and trim the hedges",
    dueDate: "2023-06-19",
    priority: "low",
    completed: false,
  },
  {
    id: 13,
    title: "Dentist appointment",
    description: "Get a routine dental cleaning",
    dueDate: "2023-06-28",
    priority: "medium",
    completed: false,
  },
  {
    id: 14,
    title: "Plan vacation",
    description: "Research destinations and book flights/hotels",
    dueDate: "2023-07-10",
    priority: "low",
    completed: false,
  },
  {
    id: 15,
    title: "Finish project",
    description: "Complete the final tasks for a work project",
    dueDate: "2023-06-22",
    priority: "high",
    completed: false,
  },
  {
    id: 16,
    title: "Buy gifts",
    description: "Purchase birthday gifts for friends and family",
    dueDate: "2023-06-27",
    priority: "medium",
    completed: false,
  },
  {
    id: 17,
    title: "Organize files",
    description: "Sort through digital files and delete unnecessary ones",
    dueDate: "2023-07-05",
    priority: "low",
    completed: false,
  },
  {
    id: 18,
    title: "Learn new skill",
    description: "Take an online course or watch tutorials",
    dueDate: "2023-08-01",
    priority: "medium",
    completed: false,
  },
  {
    id: 19,
    title: "Volunteer",
    description: "Donate time to a local charity or organization",
    dueDate: "2023-06-24",
    priority: "low",
    completed: false,
  },
  {
    id: 20,
    title: "Declutter home",
    description: "Go through each room and get rid of unnecessary items",
    dueDate: "2023-07-15",
    priority: "medium",
    completed: false,
  },
  {
    id: 21,
    title: "Attend networking event",
    description: "Meet new professionals in your industry",
    dueDate: "2023-06-29",
    priority: "medium",
    completed: false,
  },
  {
    id: 22,
    title: "Update resume",
    description: "Revise and polish your resume",
    dueDate: "2023-07-10",
    priority: "high",
    completed: false,
  },
  {
    id: 23,
    title: "Plan party",
    description: "Organize a birthday or holiday party",
    dueDate: "2023-07-20",
    priority: "low",
    completed: false,
  },
  {
    id: 24,
    title: "Donate clothes",
    description: "Go through closet and donate unwanted items",
    dueDate: "2023-06-30",
    priority: "low",
    completed: false,
  },
  {
    id: 25,
    title: "Meal plan",
    description: "Plan out meals for the upcoming week",
    dueDate: "2023-06-11",
    priority: "medium",
    completed: false,
  },
  {
    id: 26,
    title: "Clean out garage",
    description: "Organize and declutter the garage",
    dueDate: "2023-07-08",
    priority: "low",
    completed: false,
  },
  {
    id: 27,
    title: "Attend concert",
    description: "Buy tickets and plan transportation",
    dueDate: "2023-07-15",
    priority: "low",
    completed: false,
  },
  {
    id: 28,
    title: "Renew subscriptions",
    description: "Renew magazine, streaming, or software subscriptions",
    dueDate: "2023-06-25",
    priority: "medium",
    completed: false,
  },
  {
    id: 29,
    title: "Research new hobby",
    description: "Look into starting a new hobby or activity",
    dueDate: "2023-07-01",
    priority: "low",
    completed: false,
  },
  {
    id: 30,
    title: "Organize photos",
    description: "Sort and backup digital photos",
    dueDate: "2023-07-10",
    priority: "low",
    completed: false,
  },
];
